/******************************************************************************
*  Generated by PSoC Designer 5.0.985.0
******************************************************************************/
#include <m8c.h>
// receiver_configLCD_1D4 address and mask defines
#pragma	ioport	receiver_configLCD_1D4_Data_ADDR:	0x8
BYTE			receiver_configLCD_1D4_Data_ADDR;
#pragma	ioport	receiver_configLCD_1D4_DriveMode_0_ADDR:	0x108
BYTE			receiver_configLCD_1D4_DriveMode_0_ADDR;
#pragma	ioport	receiver_configLCD_1D4_DriveMode_1_ADDR:	0x109
BYTE			receiver_configLCD_1D4_DriveMode_1_ADDR;
#pragma	ioport	receiver_configLCD_1D4_DriveMode_2_ADDR:	0xb
BYTE			receiver_configLCD_1D4_DriveMode_2_ADDR;
#pragma	ioport	receiver_configLCD_1D4_GlobalSelect_ADDR:	0xa
BYTE			receiver_configLCD_1D4_GlobalSelect_ADDR;
#pragma	ioport	receiver_configLCD_1D4_IntCtrl_0_ADDR:	0x10a
BYTE			receiver_configLCD_1D4_IntCtrl_0_ADDR;
#pragma	ioport	receiver_configLCD_1D4_IntCtrl_1_ADDR:	0x10b
BYTE			receiver_configLCD_1D4_IntCtrl_1_ADDR;
#pragma	ioport	receiver_configLCD_1D4_IntEn_ADDR:	0x9
BYTE			receiver_configLCD_1D4_IntEn_ADDR;
#define receiver_configLCD_1D4_MASK 0x1
// receiver_configLCD_1D4 Shadow defines
//   receiver_configLCD_1D4_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define receiver_configLCD_1D4_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   receiver_configLCD_1D4_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define receiver_configLCD_1D4_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   receiver_configLCD_1D4_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define receiver_configLCD_1D4_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// receiver_configLCD_1D5 address and mask defines
#pragma	ioport	receiver_configLCD_1D5_Data_ADDR:	0x8
BYTE			receiver_configLCD_1D5_Data_ADDR;
#pragma	ioport	receiver_configLCD_1D5_DriveMode_0_ADDR:	0x108
BYTE			receiver_configLCD_1D5_DriveMode_0_ADDR;
#pragma	ioport	receiver_configLCD_1D5_DriveMode_1_ADDR:	0x109
BYTE			receiver_configLCD_1D5_DriveMode_1_ADDR;
#pragma	ioport	receiver_configLCD_1D5_DriveMode_2_ADDR:	0xb
BYTE			receiver_configLCD_1D5_DriveMode_2_ADDR;
#pragma	ioport	receiver_configLCD_1D5_GlobalSelect_ADDR:	0xa
BYTE			receiver_configLCD_1D5_GlobalSelect_ADDR;
#pragma	ioport	receiver_configLCD_1D5_IntCtrl_0_ADDR:	0x10a
BYTE			receiver_configLCD_1D5_IntCtrl_0_ADDR;
#pragma	ioport	receiver_configLCD_1D5_IntCtrl_1_ADDR:	0x10b
BYTE			receiver_configLCD_1D5_IntCtrl_1_ADDR;
#pragma	ioport	receiver_configLCD_1D5_IntEn_ADDR:	0x9
BYTE			receiver_configLCD_1D5_IntEn_ADDR;
#define receiver_configLCD_1D5_MASK 0x2
// receiver_configLCD_1D5 Shadow defines
//   receiver_configLCD_1D5_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define receiver_configLCD_1D5_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   receiver_configLCD_1D5_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define receiver_configLCD_1D5_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   receiver_configLCD_1D5_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define receiver_configLCD_1D5_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// receiver_configLCD_1D6 address and mask defines
#pragma	ioport	receiver_configLCD_1D6_Data_ADDR:	0x8
BYTE			receiver_configLCD_1D6_Data_ADDR;
#pragma	ioport	receiver_configLCD_1D6_DriveMode_0_ADDR:	0x108
BYTE			receiver_configLCD_1D6_DriveMode_0_ADDR;
#pragma	ioport	receiver_configLCD_1D6_DriveMode_1_ADDR:	0x109
BYTE			receiver_configLCD_1D6_DriveMode_1_ADDR;
#pragma	ioport	receiver_configLCD_1D6_DriveMode_2_ADDR:	0xb
BYTE			receiver_configLCD_1D6_DriveMode_2_ADDR;
#pragma	ioport	receiver_configLCD_1D6_GlobalSelect_ADDR:	0xa
BYTE			receiver_configLCD_1D6_GlobalSelect_ADDR;
#pragma	ioport	receiver_configLCD_1D6_IntCtrl_0_ADDR:	0x10a
BYTE			receiver_configLCD_1D6_IntCtrl_0_ADDR;
#pragma	ioport	receiver_configLCD_1D6_IntCtrl_1_ADDR:	0x10b
BYTE			receiver_configLCD_1D6_IntCtrl_1_ADDR;
#pragma	ioport	receiver_configLCD_1D6_IntEn_ADDR:	0x9
BYTE			receiver_configLCD_1D6_IntEn_ADDR;
#define receiver_configLCD_1D6_MASK 0x4
// receiver_configLCD_1D6 Shadow defines
//   receiver_configLCD_1D6_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define receiver_configLCD_1D6_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   receiver_configLCD_1D6_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define receiver_configLCD_1D6_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   receiver_configLCD_1D6_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define receiver_configLCD_1D6_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// receiver_configLCD_1D7 address and mask defines
#pragma	ioport	receiver_configLCD_1D7_Data_ADDR:	0x8
BYTE			receiver_configLCD_1D7_Data_ADDR;
#pragma	ioport	receiver_configLCD_1D7_DriveMode_0_ADDR:	0x108
BYTE			receiver_configLCD_1D7_DriveMode_0_ADDR;
#pragma	ioport	receiver_configLCD_1D7_DriveMode_1_ADDR:	0x109
BYTE			receiver_configLCD_1D7_DriveMode_1_ADDR;
#pragma	ioport	receiver_configLCD_1D7_DriveMode_2_ADDR:	0xb
BYTE			receiver_configLCD_1D7_DriveMode_2_ADDR;
#pragma	ioport	receiver_configLCD_1D7_GlobalSelect_ADDR:	0xa
BYTE			receiver_configLCD_1D7_GlobalSelect_ADDR;
#pragma	ioport	receiver_configLCD_1D7_IntCtrl_0_ADDR:	0x10a
BYTE			receiver_configLCD_1D7_IntCtrl_0_ADDR;
#pragma	ioport	receiver_configLCD_1D7_IntCtrl_1_ADDR:	0x10b
BYTE			receiver_configLCD_1D7_IntCtrl_1_ADDR;
#pragma	ioport	receiver_configLCD_1D7_IntEn_ADDR:	0x9
BYTE			receiver_configLCD_1D7_IntEn_ADDR;
#define receiver_configLCD_1D7_MASK 0x8
// receiver_configLCD_1D7 Shadow defines
//   receiver_configLCD_1D7_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define receiver_configLCD_1D7_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   receiver_configLCD_1D7_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define receiver_configLCD_1D7_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   receiver_configLCD_1D7_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define receiver_configLCD_1D7_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// receiver_configLCD_1E address and mask defines
#pragma	ioport	receiver_configLCD_1E_Data_ADDR:	0x8
BYTE			receiver_configLCD_1E_Data_ADDR;
#pragma	ioport	receiver_configLCD_1E_DriveMode_0_ADDR:	0x108
BYTE			receiver_configLCD_1E_DriveMode_0_ADDR;
#pragma	ioport	receiver_configLCD_1E_DriveMode_1_ADDR:	0x109
BYTE			receiver_configLCD_1E_DriveMode_1_ADDR;
#pragma	ioport	receiver_configLCD_1E_DriveMode_2_ADDR:	0xb
BYTE			receiver_configLCD_1E_DriveMode_2_ADDR;
#pragma	ioport	receiver_configLCD_1E_GlobalSelect_ADDR:	0xa
BYTE			receiver_configLCD_1E_GlobalSelect_ADDR;
#pragma	ioport	receiver_configLCD_1E_IntCtrl_0_ADDR:	0x10a
BYTE			receiver_configLCD_1E_IntCtrl_0_ADDR;
#pragma	ioport	receiver_configLCD_1E_IntCtrl_1_ADDR:	0x10b
BYTE			receiver_configLCD_1E_IntCtrl_1_ADDR;
#pragma	ioport	receiver_configLCD_1E_IntEn_ADDR:	0x9
BYTE			receiver_configLCD_1E_IntEn_ADDR;
#define receiver_configLCD_1E_MASK 0x10
// receiver_configLCD_1E Shadow defines
//   receiver_configLCD_1E_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define receiver_configLCD_1E_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   receiver_configLCD_1E_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define receiver_configLCD_1E_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   receiver_configLCD_1E_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define receiver_configLCD_1E_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// receiver_configLCD_1RS address and mask defines
#pragma	ioport	receiver_configLCD_1RS_Data_ADDR:	0x8
BYTE			receiver_configLCD_1RS_Data_ADDR;
#pragma	ioport	receiver_configLCD_1RS_DriveMode_0_ADDR:	0x108
BYTE			receiver_configLCD_1RS_DriveMode_0_ADDR;
#pragma	ioport	receiver_configLCD_1RS_DriveMode_1_ADDR:	0x109
BYTE			receiver_configLCD_1RS_DriveMode_1_ADDR;
#pragma	ioport	receiver_configLCD_1RS_DriveMode_2_ADDR:	0xb
BYTE			receiver_configLCD_1RS_DriveMode_2_ADDR;
#pragma	ioport	receiver_configLCD_1RS_GlobalSelect_ADDR:	0xa
BYTE			receiver_configLCD_1RS_GlobalSelect_ADDR;
#pragma	ioport	receiver_configLCD_1RS_IntCtrl_0_ADDR:	0x10a
BYTE			receiver_configLCD_1RS_IntCtrl_0_ADDR;
#pragma	ioport	receiver_configLCD_1RS_IntCtrl_1_ADDR:	0x10b
BYTE			receiver_configLCD_1RS_IntCtrl_1_ADDR;
#pragma	ioport	receiver_configLCD_1RS_IntEn_ADDR:	0x9
BYTE			receiver_configLCD_1RS_IntEn_ADDR;
#define receiver_configLCD_1RS_MASK 0x20
// receiver_configLCD_1RS Shadow defines
//   receiver_configLCD_1RS_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define receiver_configLCD_1RS_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   receiver_configLCD_1RS_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define receiver_configLCD_1RS_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   receiver_configLCD_1RS_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define receiver_configLCD_1RS_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// receiver_configLCD_1RW address and mask defines
#pragma	ioport	receiver_configLCD_1RW_Data_ADDR:	0x8
BYTE			receiver_configLCD_1RW_Data_ADDR;
#pragma	ioport	receiver_configLCD_1RW_DriveMode_0_ADDR:	0x108
BYTE			receiver_configLCD_1RW_DriveMode_0_ADDR;
#pragma	ioport	receiver_configLCD_1RW_DriveMode_1_ADDR:	0x109
BYTE			receiver_configLCD_1RW_DriveMode_1_ADDR;
#pragma	ioport	receiver_configLCD_1RW_DriveMode_2_ADDR:	0xb
BYTE			receiver_configLCD_1RW_DriveMode_2_ADDR;
#pragma	ioport	receiver_configLCD_1RW_GlobalSelect_ADDR:	0xa
BYTE			receiver_configLCD_1RW_GlobalSelect_ADDR;
#pragma	ioport	receiver_configLCD_1RW_IntCtrl_0_ADDR:	0x10a
BYTE			receiver_configLCD_1RW_IntCtrl_0_ADDR;
#pragma	ioport	receiver_configLCD_1RW_IntCtrl_1_ADDR:	0x10b
BYTE			receiver_configLCD_1RW_IntCtrl_1_ADDR;
#pragma	ioport	receiver_configLCD_1RW_IntEn_ADDR:	0x9
BYTE			receiver_configLCD_1RW_IntEn_ADDR;
#define receiver_configLCD_1RW_MASK 0x40
// receiver_configLCD_1RW Shadow defines
//   receiver_configLCD_1RW_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define receiver_configLCD_1RW_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   receiver_configLCD_1RW_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define receiver_configLCD_1RW_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   receiver_configLCD_1RW_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define receiver_configLCD_1RW_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
