/******************************************************************************
*  Generated by PSoC Designer 5.0.985.0
******************************************************************************/
#include <m8c.h>
// pc_listenerAnalogColumn_InputMUX_1 address and mask defines
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_Data_ADDR:	0x0
BYTE			pc_listenerAnalogColumn_InputMUX_1_Data_ADDR;
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_DriveMode_0_ADDR:	0x100
BYTE			pc_listenerAnalogColumn_InputMUX_1_DriveMode_0_ADDR;
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_DriveMode_1_ADDR:	0x101
BYTE			pc_listenerAnalogColumn_InputMUX_1_DriveMode_1_ADDR;
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_DriveMode_2_ADDR:	0x3
BYTE			pc_listenerAnalogColumn_InputMUX_1_DriveMode_2_ADDR;
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_GlobalSelect_ADDR:	0x2
BYTE			pc_listenerAnalogColumn_InputMUX_1_GlobalSelect_ADDR;
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_IntCtrl_0_ADDR:	0x102
BYTE			pc_listenerAnalogColumn_InputMUX_1_IntCtrl_0_ADDR;
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_IntCtrl_1_ADDR:	0x103
BYTE			pc_listenerAnalogColumn_InputMUX_1_IntCtrl_1_ADDR;
#pragma	ioport	pc_listenerAnalogColumn_InputMUX_1_IntEn_ADDR:	0x1
BYTE			pc_listenerAnalogColumn_InputMUX_1_IntEn_ADDR;
#define pc_listenerAnalogColumn_InputMUX_1_MASK 0x40
