//*****************************************************************************
//*****************************************************************************
//  FILENAME:  LCD_3.h
//  Version: 1.5, Updated on 2009/7/10 at 10:44:58
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION:  LCD User Module C Language interface file for the
//                M8C based PSoC family of devices.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2001-2006. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


#include <m8c.h>

#define LCD_3_BARGRAPH_ENABLE 1

/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LCD_3_Start
#pragma fastcall16  LCD_3_Init
#pragma fastcall16  LCD_3_Control
#pragma fastcall16  LCD_3_WriteData
#pragma fastcall16  LCD_3_PrString
#pragma fastcall16  LCD_3_PrCString
#pragma fastcall16  LCD_3_PrHexByte
#pragma fastcall16  LCD_3_PrHexInt
#pragma fastcall16  LCD_3_Position
#pragma fastcall16  LCD_3_Delay50uTimes
#pragma fastcall16  LCD_3_Delay50u

#if ( LCD_3_BARGRAPH_ENABLE )
#pragma fastcall16  LCD_3_InitBG
#pragma fastcall16  LCD_3_DrawBG
#pragma fastcall16  LCD_3_InitVBG
#pragma fastcall16  LCD_3_DrawVBG
#endif

//-------------------------------------------------
// Prototypes of the LCD_3 API.
//-------------------------------------------------

extern void  LCD_3_Start(void);
extern void  LCD_3_Init(void);
extern void  LCD_3_Control(BYTE bData);
extern void  LCD_3_WriteData(BYTE bData);
extern void  LCD_3_PrString(char * sRamString);
extern void  LCD_3_PrCString(const char * sRomString);
extern void  LCD_3_Position(BYTE bRow, BYTE bCol);
extern void  LCD_3_PrHexByte(BYTE bValue);
extern void  LCD_3_PrHexInt(INT iValue);

extern void  LCD_3_Delay50uTimes(BYTE bTimes);
extern void  LCD_3_Delay50u(void);

// Do not use, will be removed in future version.
extern void  LCD_3_Write_Data(BYTE bData);
#pragma fastcall16 LCD_3_Write_Data
//


#if ( LCD_3_BARGRAPH_ENABLE )
extern void  LCD_3_InitBG(BYTE bBGType);
extern void  LCD_3_InitVBG(void);
extern void  LCD_3_DrawVBG(BYTE bRow, BYTE bCol, BYTE bHeight, BYTE bPixelRowEnd);
extern void  LCD_3_DrawBG(BYTE bRow, BYTE bCol, BYTE bLen, BYTE bPixelColEnd);


#define LCD_3_SOLID_BG                      0x00
#define LCD_3_LINE_BG                       0x01


#endif

//-------------------------------------------------
// Defines for LCD_3 API's.
//-------------------------------------------------
#define LCD_3_DISP_ON                       0x0C
#define LCD_3_DISP_OFF                      0x08
#define LCD_3_DISP_BLANK                    0x0A
#define LCD_3_DISP_CLEAR_HOME               0x01
#define LCD_3_CURSOR_ON                     0x0E
#define LCD_3_CURSOR_OFF                    0x0C
#define LCD_3_CURSOR_WINK                   0x0D
#define LCD_3_CURSOR_BLINK                  0x0F
#define LCD_3_CURSOR_SH_LEFT                0x10
#define LCD_3_CURSOR_SH_RIGHT               0x14
#define LCD_3_CURSOR_HOME                   0x02
#define LCD_3_CURSOR_LEFT                   0x04
#define LCD_3_CURSOR_RIGHT                  0x06

#define LCD_3_PORT_MASK                     0x7F
//------------------------------------------------------
//  Register Address Constants for  LCD_3
//------------------------------------------------------

#define LCD_3_Port                        PRT2DR
#define LCD_3_PortMode0                   PRT2DM0
#define LCD_3_PortMode1                   PRT2DM1

// end of file LCD_3.h
