;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: POWER_CHECK.asm
;;   Version: 1.1, Updated on 2009/7/10 at 10:41:37
;;  Generated by PSoC Designer 5.0.985.0
;;
;;  DESCRIPTION: Assembler source for the ADCINC A/D Converter
;;               User Module with 1st-order modulator.
;;
;;  NOTE: User Module APIs conform to the fastcall16 convention for marshalling
;;        arguments and observe the associated "Registers are volatile" policy.
;;        This means it is the caller's responsibility to preserve any values
;;        in the X and A registers that are still needed after the API
;;        function returns. Even though these registers may be preserved now,
;;        there is no guarantee they will be preserved in future releases.
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress MicroSystems 2000-2004. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"

include "POWER_CHECK.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  POWER_CHECK_Start
export _POWER_CHECK_Start
export  POWER_CHECK_SetPower
export _POWER_CHECK_SetPower
export  POWER_CHECK_Stop
export _POWER_CHECK_Stop
export  POWER_CHECK_GetSamples
export _POWER_CHECK_GetSamples
export  POWER_CHECK_StopADC
export _POWER_CHECK_StopADC
export  POWER_CHECK_fIsDataAvailable
export _POWER_CHECK_fIsDataAvailable
export  POWER_CHECK_iClearFlagGetData
export _POWER_CHECK_iClearFlagGetData
export  POWER_CHECK_wClearFlagGetData
export _POWER_CHECK_wClearFlagGetData
export  POWER_CHECK_cClearFlagGetData
export _POWER_CHECK_cClearFlagGetData
export  POWER_CHECK_bClearFlagGetData
export _POWER_CHECK_bClearFlagGetData
export  POWER_CHECK_iGetData
export _POWER_CHECK_iGetData
export  POWER_CHECK_wGetData
export _POWER_CHECK_wGetData
export  POWER_CHECK_bGetData
export _POWER_CHECK_bGetData
export  POWER_CHECK_cGetData
export _POWER_CHECK_cGetData
export  POWER_CHECK_fClearFlag
export _POWER_CHECK_fClearFlag
export  POWER_CHECK_WritePulseWidth
export _POWER_CHECK_WritePulseWidth


AREA bss (RAM,REL)

;-----------------------------------------------
;  Constant Definitions
;-----------------------------------------------

;-----------------------------------------------
; Variable Allocation
;-----------------------------------------------


AREA UserModules (ROM, REL)

.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_Start
;
;  DESCRIPTION: Applies power setting to the module's analog PSoc block.
;               and starts the PWM
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    The A register contains the power setting.
;  RETURNS:      Nothing.
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 POWER_CHECK_Start:
_POWER_CHECK_Start:
   RAM_PROLOGUE RAM_USE_CLASS_1
   call  POWER_CHECK_SetPower
   POWER_CHECK_RESET_INTEGRATOR_M
   mov   reg[POWER_CHECK_PWMdr1],ffh
   or    reg[POWER_CHECK_PWMcr0],01h                 ; start PWM
   RAM_EPILOGUE RAM_USE_CLASS_1
   ret
.ENDSECTION

   
.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_SetPower
;
;  DESCRIPTION: Applies power setting to the module's analog PSoc block.
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    The A register contains the power setting.
;  RETURNS:      Nothing.
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 POWER_CHECK_SetPower:
_POWER_CHECK_SetPower:
   RAM_PROLOGUE RAM_USE_CLASS_2
   mov  X,SP                                     ; Set up Stack frame
   and  A,03h                                    ; Ensure value is legal
   push A
   mov  A,reg[POWER_CHECK_AtoDcr3]               ; First SC block:
   and  A,~03h                                   ;   clear power bits to zero
   or   A,[ X ]                                  ;   establish new value
   mov  reg[POWER_CHECK_AtoDcr3],A               ;   change the actual setting
   pop  A
   RAM_EPILOGUE RAM_USE_CLASS_2
   ret
.ENDSECTION

.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_Stop
;
;  DESCRIPTION:   Removes power from the module's analog PSoc block.
;                 and turns off PWM
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:     None.
;  RETURNS:       Nothing.
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 POWER_CHECK_Stop:
_POWER_CHECK_Stop:
   RAM_PROLOGUE RAM_USE_CLASS_1
   POWER_CHECK_STOPADC_M
   and  reg[POWER_CHECK_AtoDcr3], ~03h
   and  reg[POWER_CHECK_PWMcr0], ~01h ; stop PWM
   RAM_EPILOGUE RAM_USE_CLASS_1
   ret
.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_GetSamples
;
;  DESCRIPTION: Activates interrupts for this user module and begins sampling.
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    A register contain number of samples
;  RETURNS:      Nothing.
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified: 
;          CUR_PP
;
 POWER_CHECK_GetSamples:
_POWER_CHECK_GetSamples:
   RAM_PROLOGUE RAM_USE_CLASS_4
   RAM_SETPAGE_CUR >POWER_CHECK_fMode
   POWER_CHECK_ENABLE_INTEGRATOR_M
   mov [POWER_CHECK_fMode],0
   mov [POWER_CHECK_bState],0
   mov [POWER_CHECK_bNumSamples],A
   mov A, reg[POWER_CHECK_PWMdr2]
   jnz  .SkipPulseWrite
   mov reg[POWER_CHECK_PWMdr2], 1
.SkipPulseWrite:

   M8C_SetBank1
   and reg[E7h], 3Fh             ; if we are in 29xxx or 24x94   
   or  reg[E7h], 40h             ; then set to incremental Mode
   M8C_SetBank0

   POWER_CHECK_STARTADC_M  ;enable interrupt 
   RAM_EPILOGUE RAM_USE_CLASS_4 
   ret
.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_StopADC
;
;  DESCRIPTION: Shuts down the A/D is an orderly manner.  The interrupt
;               is disabled but the PWM output is still active.
;               Integrator is reset
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    None.
;  RETURNS:      Nothing.
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 POWER_CHECK_StopADC:
_POWER_CHECK_StopADC:
   RAM_PROLOGUE RAM_USE_CLASS_1
   M8C_SetBank1
   and reg[E7h], 3Fh             ; if we are in 29xxx or 24x94   
   or  reg[E7h], 80h             ; then set to incremental Mode
   M8C_SetBank0
   POWER_CHECK_STOPADC_M
   POWER_CHECK_RESET_INTEGRATOR_M
   RAM_EPILOGUE RAM_USE_CLASS_1 
   ret
.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_fIsDataAvailable
;
;  DESCRIPTION: Returns the status of the A/D Data
;-----------------------------------------------------------------------------
;  ARGUMENTS:    None.
;  RETURNS:      fastcall BOOL DataAvailable returned in the A register
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified: 
;          CUR_PP
;
 POWER_CHECK_fIsDataAvailable:
_POWER_CHECK_fIsDataAvailable:
   RAM_PROLOGUE RAM_USE_CLASS_4
   POWER_CHECK_fIsDataAvailable_M   
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME:  POWER_CHECK_iClearFlagGetData
;                  POWER_CHECK_wClearFlagGetData
;
;  DESCRIPTION:    Clears the fStatus and places ADC data in iResult A/D.
;                  Flag is checked after trandfer to insure valid data.
;                  available. Also clears the DATA_READY flag. 
;-----------------------------------------------------------------------------
;  ARGUMENTS:    None.
;  RETURNS:      fastcall int iResult returned in the X and A register
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified: 
;          CUR_PP
;
 POWER_CHECK_iClearFlagGetData:
_POWER_CHECK_iClearFlagGetData:
 POWER_CHECK_wClearFlagGetData:
_POWER_CHECK_wClearFlagGetData:
   RAM_PROLOGUE RAM_USE_CLASS_4
   POWER_CHECK_iClearFlagGetData_M   
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME:  POWER_CHECK_cClearFlagGetData
;                  POWER_CHECK_bClearFlagGetData
;
;  DESCRIPTION:    Clears the fStatus and places ADC data in iResult A/D.
;-----------------------------------------------------------------------------
;  ARGUMENTS:    None.
;  RETURNS:      fastcall int iResult returned in the X and A register
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified: 
;          CUR_PP
;
 POWER_CHECK_cClearFlagGetData:
_POWER_CHECK_cClearFlagGetData:
 POWER_CHECK_bClearFlagGetData:
_POWER_CHECK_bClearFlagGetData:
   RAM_PROLOGUE RAM_USE_CLASS_4
   POWER_CHECK_bClearFlagGetData_M     
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION
.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME:  POWER_CHECK_iGetData
;				   POWER_CHECK_wGetData
;
;  DESCRIPTION:     Returns the data from the A/D.  Does not check if data is
;                   available.
;-----------------------------------------------------------------------------
;  ARGUMENTS:    None.
;  RETURNS:      fastcall int iResult is returned in the X,A registers
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified: 
;          CUR_PP
;
 POWER_CHECK_iGetData:
_POWER_CHECK_iGetData:
 POWER_CHECK_wGetData:
_POWER_CHECK_wGetData:
   RAM_PROLOGUE RAM_USE_CLASS_4
   POWER_CHECK_wGetData_M          
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION
.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME:  POWER_CHECK_bGetData
;                  POWER_CHECK_cGetData
;
;  DESCRIPTION:     Returns the data from the A/D.  Does not check if data is
;                   available.
;-----------------------------------------------------------------------------
;  ARGUMENTS:    None.
;  RETURNS:      fastcall CHAR cData returned in the A register
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified: 
;          CUR_PP
;
 POWER_CHECK_bGetData:
_POWER_CHECK_bGetData:
 POWER_CHECK_cGetData:
_POWER_CHECK_cGetData:
   RAM_PROLOGUE RAM_USE_CLASS_4
   POWER_CHECK_cGetData_M        
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_fClearFlag
;
;  DESCRIPTION: Clears the data ready flag.
;-----------------------------------------------------------------------------
;  ARGUMENTS:    None.
;  RETURNS:      Nothing.
;  SIDE EFFECTS: 
;    The DATA_READY flag is cleared.
;    
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified: 
;          CUR_PP
;
 POWER_CHECK_fClearFlag:
_POWER_CHECK_fClearFlag:
   RAM_PROLOGUE RAM_USE_CLASS_4
   POWER_CHECK_fClearFlag_M    
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: POWER_CHECK_WritePulseWidth
;
;  DESCRIPTION:
;     Write the 8-bit period value into the compare register (DR2).
;-----------------------------------------------------------------------------
;
;  ARGUMENTS: fastcall BYTE bPeriodValue (passed in A)
;  RETURNS:   Nothing
;  SIDE EFFECTS:
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 POWER_CHECK_WritePulseWidth:
_POWER_CHECK_WritePulseWidth:
   RAM_PROLOGUE RAM_USE_CLASS_1
   POWER_CHECK_WritePulseWidth_M  
   RAM_EPILOGUE RAM_USE_CLASS_1
   ret
.ENDSECTION

; End of File POWER_CHECK.asm
